config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:index, :new, :create]
  end
  root "restaurants#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category,  presence: true, inclusion: { in: CATEGORIES}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5,  only_integer: true }
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :set_restaurant, only: %i[show]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant, notice: "Restaurant was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to @restaurant, notice: "Review posted"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container text-center pt-5 px-0 w-50">
  <div class="d-flex justify-content-between mb-2">
    <h1>Restaurants</h1>
    <p><%= link_to "Create restaurant", new_restaurant_path, class: "btn btn-primary" %></p>
  </div>
  <div>
    <ul class="list-group">
      <% @restaurants.each do |restaurant| %>
      <li class="list-group-item py-3"><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container pt-5 px-0 w-50">
  <h1 class="center mb-5">Create restaurant</h1>
  <%= simple_form_for(@restaurant) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number, as: :tel %>
    <%= f.input :category, collection: Restaurant::CATEGORIES %>
    <%= f.submit class: "btn btn-primary" %>
    <%= link_to "Back to index", restaurants_path, class: "btn  btn-secondary"%>
  <% end %>
</div>

app/views/restaurants/show.html.erb
<div class="container text-center p-5">
  <h1><%= @restaurant.name %></h1>
  <div class="container w-50 p-2 mb-3">
    <ul class="list-group">
      <li class="list-group-item">
        <h3><%= @restaurant.category.capitalize %></h3>
        <p>📍 <%= @restaurant.address %></p>
        <p>☎️ <%= @restaurant.phone_number %></p>
      </li>
      <li class="list-group-item">
        <h3>Reviews</h3>
        <ul class="list-group">
        <% @restaurant.reviews.each do |review| %>
          <li class="list-group-item"><p><%= review.rating%>⭐</p><p><%= review.content %></p></li>
        <% end %>
        </ul>
      </li>
    </ul>
    
  </div>
  
<%= link_to "Leave a review", new_restaurant_review_path(@restaurant), class: "btn btn-primary"%>
<%= link_to "Back to index", restaurants_path, class: "btn  btn-secondary"%>
</div>

app/views/reviews/new.html.erb
<div class="container pt-5 px-0 w-50">
  <h1 class="center mb-5">Write a review for <%= @restaurant.name %></h1>
  <%= simple_form_for([@restaurant, @review]) do |f| %>
    <%= f.input :rating, collection: (0..5) %>
    <%= f.input :content %>
    <%= f.submit class: "btn btn-primary" %>
    <%= link_to "Back to index", restaurants_path, class: "btn  btn-secondary" %>
  <% end %>
</div>